package me.hifei.rewardchests.coreapi.hook;

public enum HookMethod {
    METHOD_GET_OWNER,
    METHOD_GET_PARTS,
    METHOD_GET_LOOT_TABLE,
    METHOD_SET_OWNER,
    METHOD_REMOVE_PART,
    METHOD_GET_CHEST_INFO_ITEM,
    METHOD_ADD_PART,
    METHOD_GIVE,
    METHOD_OPEN_GUI_TO_OWNER,
    METHOD_LOOT,
    METHOD_TICK,
    METHOD_DELETE_FROM_PLAYER,
    EXTENDED_SET_LOOT_TABLE,
    EXTENDED_SET_CHEST_INFO_ITEM,
    EXTENDED_SET_CHEST_INFO_ITEM_CONVERTER,
    EXTENDED_GET_CHEST_INFO_ITEM_CONVERTER,
    EXTENDED_GET_PART_LIST,
    EXTENDED_SET_LOOT_FORCE
}
